### ISSUE TITLE
Progress?

### ISSUE THREAD

**Issue by leoheck** [IDerr/Goodix92#1]
Hi, do you have any progress so far?

**Comment by IDerr** [comment]
Hello 9570 buddy,
I had a lot of exams and a lot of projects, but I'm still working on it.
It's harder to reverse engineer it, because the fingerprint sensor uses Intel SGX , so it's not as easy as the 9560 fingerprint sensor.

That's it for the moment, I'll try to update this repo more often ahah

**Comment by leoheck** [comment]
haha no rush! let me know if I can do something to help you.

**Comment by leoheck** [comment]
Adding a reference here
https://github.com/hmaarrfk/Validity91/issues/10#issuecomment-433748204

**Comment by leoheck** [comment]
https://gitter.im/Goodix92/Lobby

**Comment by IDerr** [comment]
Since, I have added the gitter badge on the front page, can I close this ?

**Comment by leoheck** [comment]
Sure!
