### ISSUE TITLE
Don't redistribute the windows dll

### ISSUE THREAD

**Issue by ao2** [IDerr/Goodix92#3]
I'd suggest against redistributing the windows dll, to avoid any legal problem.

The version of the file and maybe a hash can be communicated instead, to allow interested developers to get exactly the same file which corresponds to the IDA database.

**Comment by IDerr** [comment]
Hello, The ddl is now on git and goodix doesn't seem to care about this ftm. 
But thanks for your prevention, I'll remove it for the next commit.
