### ISSUE TITLE
Does this repo relates also to Dell XPS 9380 (2019) ?

### ISSUE THREAD

**Issue by jurosh** [IDerr/Goodix92#6]
Dell released new laptop (13" version with webcam on top) - XPS 9380. I was able to find out that it's using `Goodix Fingerprint Device` by running `lshw` command.

```
/0/100/14/0/a    communication  Goodix Fingerprint Device
```

Is there way how to know if this is same fingerprint device like on previous dell - Dell XPS 9570 fingerprint sensor (27c6:5395) ?

**Comment by jurosh** [comment]
Now running also `lsusb` and there is one output very similar. It is:

```
Bus 001 Device 006: ID 27c6:5385
```

So the only difference is only here: 27c6:53<b>(9->8)</b>5

Not sure what that mean, if it's completely different sensor or very similar one.

**Comment by IDerr** [comment]
Hello jurosh,
The Device ID (the last 4 digits) are different, but I suspect this is nearly the same device.

@ao2 has created a tool to dump infos of your fingerprint device : 
https://gitlab.collabora.com/ao2/goodix_fp_dump

If it's printing something, the device is not really different from the 9370 :D
You can find more infos here:
https://gitlab.freedesktop.org/libfprint/libfprint/issues/43

**Comment by ao2** [comment]
Yeah AFAIK the device on the 9380 is basically the same as the one on the 9370 and 9570.

You can find info on different Goodix devices here: https://gitlab.freedesktop.org/libfprint/libfprint/issues?scope=all&utf8=%E2%9C%93&state=opened&search=27c6

**Comment by IDerr** [comment]
I think I can close this
