### ISSUE TITLE
Is dell xps 15 2 in 1 9575 close enough to use this when it's done?

### ISSUE THREAD

**Issue by andrewlin0410** [IDerr/Goodix92#8]

**Comment by one-mb** [comment]
I'm not sure what the aim of your question is, but I myself have the same device id on a currently recent Precision 5540 model. So in case there are any possible solutions I am also willing to test them.

**Comment by andrewlin0410** [comment]
I meant if the hardware is close enough so this repository can be used for it as well. What do you mean the same device id? Do you mean the fingerprint sensors are the same?

**Comment by one-mb** [comment]
> Do you mean the fingerprint sensors are the same?

Basically, yes. If the USB device id is the same, the device and vendor shall be the same.

**Comment by IDerr** [comment]
Can you send your "lsusb" output here ?

**Comment by one-mb** [comment]
> Can you send your "lsusb" output here ?

Sorry took me some days to get back to this.... 
Here it is: 
```
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 27c6:5395
Bus 001 Device 002: ID 8087:0025 Intel Corp. 
Bus 001 Device 004: ID 0c45:6723 Microdia 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

**Comment by IDerr** [comment]
It is exactly the same as mine, so it'll be ok for you too :D

**Comment by IDerr** [comment]
I added it to the Readme.md
Thanks for your quick answer.
