### ISSUE TITLE
Does this allow usage of the fingerprint sensor within Linux?

### ISSUE THREAD

**Issue by mvarendorff** [IDerr/Goodix92#9]
I read through the docs and (think I) understand that the docs guide helps to set things to up use the fingerprint sensor within a Windows VM.

Does this also allow me to use the fingerprint sensor to unlock my Linux laptop in Windows Hello fashion?

**Comment by IDerr** [comment]
The driver has not been fully decompiled yet, it needs to be analyzed and reimplemented for linux before that.

**Comment by mvarendorff** [comment]
Perfect, thanks! Just wanted to make sure that I understood this correctly :+1:
